### PR TITLE
Refactor Get-BTDanglingSPN to fix bugs and make it zoom

### PR DESCRIPTION
**Pull request by SamErde**
All of the updates. ☕
- Refactored to eliminate redundant DNS checks and rely on a cached copy of DNS records.
- Added a separate check to resolve FQDNs in external/excluded domains.
- Using more gatekeeping if blocks to reduce length of checks for each principal and SPN.
- Fixed bug that included SPNs with port numbers (eg: SQL) as hostnames.
- Added comment-based help because it's awesome.
- Clarified property names in the DanglingSPN output.

### CODE REVIEW

**Comment by TrimarcJake** [comment]
ZOOM is right! Nice work!

**Comment by TrimarcJake** [comment]
Ope, I was so impressed by the speed that I forgot to notice you're leaving SPNs on DCs in the list i.e. `ldap/3bffb92d-4949-47f1-b861-e24f1414a63a._msdcs.BlueTuxedo.DanglingSPNs.lol` is not a dangling SPN.

In the original `Get-BTDanglingSPN`, I filtered out SPNs on DCs that had a GUID in the host portion. Seemed to work well enough. Enhancement?

**Comment by SamErde** [comment]
Thanks! Thought I kept that DC check in but I'll review my history to see where it went.

**Comment by SamErde** [comment]
Have been AFK all day but checked on my phone. Your [GUID check is still in there](https://github.com/SamErde/BlueTuxedo/blob/5853158d42aff9032479226ef588c35b72c6daf9/Private/Get/Get-BTDanglingSPN.ps1#L89) but obviously I did something to nerf it. Will figure it out!

**Pull request merged**
